2013-12-14 05:03:35 Error: [MissingControllerException] Controller class CakephptestController could not be found.
Exception Attributes: array (
  'class' => 'CakephptestController',
  'plugin' => NULL,
)
Request URL: /cakephpTest/cakephptest/
Stack Trace:
#0 C:\xampp\htdocs\cakephpTest\app\webroot\index.php(108): Dispatcher->dispatch(Object(CakeRequest), Object(CakeResponse))
#1 {main}
2013-12-14 05:08:29 Error: [MissingActionException] Action CakephptestController::index() could not be found.
Exception Attributes: array (
  'controller' => 'CakephptestController',
  'action' => 'index',
)
Request URL: /cakephpTest/cakephptest/
Stack Trace:
#0 C:\xampp\htdocs\cakephpTest\lib\Cake\Routing\Dispatcher.php(185): Controller->invokeAction(Object(CakeRequest))
#1 C:\xampp\htdocs\cakephpTest\lib\Cake\Routing\Dispatcher.php(160): Dispatcher->_invoke(Object(CakephptestController), Object(CakeRequest), Object(CakeResponse))
#2 C:\xampp\htdocs\cakephpTest\app\webroot\index.php(108): Dispatcher->dispatch(Object(CakeRequest), Object(CakeResponse))
#3 {main}
2013-12-14 05:09:52 Error: [MissingViewException] View file "C:\xampp\htdocs\cakephpTest\app\View\Cakephptest\index.ctp" is missing.
Exception Attributes: array (
  'file' => 'C:\\xampp\\htdocs\\cakephpTest\\app\\View\\Cakephptest\\index.ctp',
)
Request URL: /cakephpTest/cakephptest/
Stack Trace:
#0 C:\xampp\htdocs\cakephpTest\lib\Cake\View\View.php(457): View->_getViewFileName(NULL)
#1 C:\xampp\htdocs\cakephpTest\lib\Cake\Controller\Controller.php(952): View->render(NULL, NULL)
#2 C:\xampp\htdocs\cakephpTest\lib\Cake\Routing\Dispatcher.php(192): Controller->render()
#3 C:\xampp\htdocs\cakephpTest\lib\Cake\Routing\Dispatcher.php(160): Dispatcher->_invoke(Object(CakephptestController), Object(CakeRequest), Object(CakeResponse))
#4 C:\xampp\htdocs\cakephpTest\app\webroot\index.php(108): Dispatcher->dispatch(Object(CakeRequest), Object(CakeResponse))
#5 {main}
2013-12-14 17:06:42 Error: [MissingActionException] Action CakephptestController::Posts() could not be found.
Exception Attributes: array (
  'controller' => 'CakephptestController',
  'action' => 'Posts',
)
Request URL: /cakephpTest/cakephptest/Posts
Stack Trace:
#0 C:\xampp\htdocs\cakephpTest\lib\Cake\Routing\Dispatcher.php(185): Controller->invokeAction(Object(CakeRequest))
#1 C:\xampp\htdocs\cakephpTest\lib\Cake\Routing\Dispatcher.php(160): Dispatcher->_invoke(Object(CakephptestController), Object(CakeRequest), Object(CakeResponse))
#2 C:\xampp\htdocs\cakephpTest\app\webroot\index.php(108): Dispatcher->dispatch(Object(CakeRequest), Object(CakeResponse))
#3 {main}
2013-12-14 17:07:52 Error: [MissingActionException] Action CakephptestController::posts() could not be found.
Exception Attributes: array (
  'controller' => 'CakephptestController',
  'action' => 'posts',
)
Request URL: /cakephpTest/cakephptest/posts
Stack Trace:
#0 C:\xampp\htdocs\cakephpTest\lib\Cake\Routing\Dispatcher.php(185): Controller->invokeAction(Object(CakeRequest))
#1 C:\xampp\htdocs\cakephpTest\lib\Cake\Routing\Dispatcher.php(160): Dispatcher->_invoke(Object(CakephptestController), Object(CakeRequest), Object(CakeResponse))
#2 C:\xampp\htdocs\cakephpTest\app\webroot\index.php(108): Dispatcher->dispatch(Object(CakeRequest), Object(CakeResponse))
#3 {main}
2013-12-14 17:09:43 Error: [MissingViewException] View file "C:\xampp\htdocs\cakephpTest\app\View\Cakephptest\posts.ctp" is missing.
Exception Attributes: array (
  'file' => 'C:\\xampp\\htdocs\\cakephpTest\\app\\View\\Cakephptest\\posts.ctp',
)
Request URL: /cakephpTest/cakephptest/posts
Stack Trace:
#0 C:\xampp\htdocs\cakephpTest\lib\Cake\View\View.php(457): View->_getViewFileName(NULL)
#1 C:\xampp\htdocs\cakephpTest\lib\Cake\Controller\Controller.php(952): View->render(NULL, NULL)
#2 C:\xampp\htdocs\cakephpTest\lib\Cake\Routing\Dispatcher.php(192): Controller->render()
#3 C:\xampp\htdocs\cakephpTest\lib\Cake\Routing\Dispatcher.php(160): Dispatcher->_invoke(Object(CakephptestController), Object(CakeRequest), Object(CakeResponse))
#4 C:\xampp\htdocs\cakephpTest\app\webroot\index.php(108): Dispatcher->dispatch(Object(CakeRequest), Object(CakeResponse))
#5 {main}
2013-12-14 17:10:15 Error: [MissingActionException] Action CakephptestController::posts() could not be found.
Exception Attributes: array (
  'controller' => 'CakephptestController',
  'action' => 'posts',
)
Request URL: /cakephpTest/cakephptest/posts
Stack Trace:
#0 C:\xampp\htdocs\cakephpTest\lib\Cake\Routing\Dispatcher.php(185): Controller->invokeAction(Object(CakeRequest))
#1 C:\xampp\htdocs\cakephpTest\lib\Cake\Routing\Dispatcher.php(160): Dispatcher->_invoke(Object(CakephptestController), Object(CakeRequest), Object(CakeResponse))
#2 C:\xampp\htdocs\cakephpTest\app\webroot\index.php(108): Dispatcher->dispatch(Object(CakeRequest), Object(CakeResponse))
#3 {main}
2013-12-14 17:26:16 Error: [MissingControllerException] Controller class CakephptestController could not be found.
Exception Attributes: array (
  'class' => 'CakephptestController',
  'plugin' => NULL,
)
Request URL: /cakephpTest/cakephptest/posts
Stack Trace:
#0 C:\xampp\htdocs\cakephpTest\app\webroot\index.php(108): Dispatcher->dispatch(Object(CakeRequest), Object(CakeResponse))
#1 {main}
2013-12-14 17:26:23 Error: [MissingControllerException] Controller class CakephptestController could not be found.
Exception Attributes: array (
  'class' => 'CakephptestController',
  'plugin' => NULL,
)
Request URL: /cakephpTest/cakephptest/
Stack Trace:
#0 C:\xampp\htdocs\cakephpTest\app\webroot\index.php(108): Dispatcher->dispatch(Object(CakeRequest), Object(CakeResponse))
#1 {main}
2013-12-14 17:51:50 Error: [MissingControllerException] Controller class PhpStorm-855404f6-46ff-4bed-86f5-546c1abfed0c.phpController could not be found.
Exception Attributes: array (
  'class' => 'PhpStorm-855404f6-46ff-4bed-86f5-546c1abfed0c.phpController',
  'plugin' => NULL,
)
Request URL: /cakephp/PhpStorm-855404f6-46ff-4bed-86f5-546c1abfed0c.php
Stack Trace:
#0 C:\xampp\htdocs\cakephp\app\webroot\index.php(108): Dispatcher->dispatch(Object(CakeRequest), Object(CakeResponse))
#1 {main}
2013-12-14 18:01:22 Error: Fatal Error (1): Maximum execution time of 30 seconds exceeded in [C:\xampp\htdocs\cakephp\lib\Cake\Error\ErrorHandler.php, line 196]
2013-12-14 18:01:22 Error: [FatalErrorException] Maximum execution time of 30 seconds exceeded
Request URL: /cakephp/
Stack Trace:
#0 C:\xampp\htdocs\cakephp\lib\Cake\Error\ErrorHandler.php(203): ErrorHandler::handleFatalError(1, 'Maximum executi...', 'C:\xampp\htdocs...', 196)
#1 [internal function]: ErrorHandler::handleError(1, 'Maximum executi...', 'C:\xampp\htdocs...', 196, Array)
#2 C:\xampp\htdocs\cakephp\lib\Cake\Core\App.php(929): call_user_func('ErrorHandler::h...', 1, 'Maximum executi...', 'C:\xampp\htdocs...', 196, Array)
#3 C:\xampp\htdocs\cakephp\lib\Cake\Core\App.php(902): App::_checkFatalError()
#4 [internal function]: App::shutdown()
#5 {main}
2013-12-14 18:02:43 Error: Fatal Error (1): Maximum execution time of 30 seconds exceeded in [C:\xampp\htdocs\cakephp\lib\Cake\Error\ErrorHandler.php, line 196]
2013-12-14 18:02:43 Error: [FatalErrorException] Maximum execution time of 30 seconds exceeded
Request URL: /cakephp/
Stack Trace:
#0 C:\xampp\htdocs\cakephp\lib\Cake\Error\ErrorHandler.php(203): ErrorHandler::handleFatalError(1, 'Maximum executi...', 'C:\xampp\htdocs...', 196)
#1 [internal function]: ErrorHandler::handleError(1, 'Maximum executi...', 'C:\xampp\htdocs...', 196, Array)
#2 C:\xampp\htdocs\cakephp\lib\Cake\Core\App.php(929): call_user_func('ErrorHandler::h...', 1, 'Maximum executi...', 'C:\xampp\htdocs...', 196, Array)
#3 C:\xampp\htdocs\cakephp\lib\Cake\Core\App.php(902): App::_checkFatalError()
#4 [internal function]: App::shutdown()
#5 {main}
2013-12-14 18:02:55 Error: Fatal Error (1): Maximum execution time of 30 seconds exceeded in [C:\xampp\htdocs\cakephp\lib\Cake\Error\ErrorHandler.php, line 196]
2013-12-14 18:02:55 Error: [FatalErrorException] Maximum execution time of 30 seconds exceeded
Request URL: /cakephp/
Stack Trace:
#0 C:\xampp\htdocs\cakephp\lib\Cake\Error\ErrorHandler.php(203): ErrorHandler::handleFatalError(1, 'Maximum executi...', 'C:\xampp\htdocs...', 196)
#1 [internal function]: ErrorHandler::handleError(1, 'Maximum executi...', 'C:\xampp\htdocs...', 196, Array)
#2 C:\xampp\htdocs\cakephp\lib\Cake\Core\App.php(929): call_user_func('ErrorHandler::h...', 1, 'Maximum executi...', 'C:\xampp\htdocs...', 196, Array)
#3 C:\xampp\htdocs\cakephp\lib\Cake\Core\App.php(902): App::_checkFatalError()
#4 [internal function]: App::shutdown()
#5 {main}
2013-12-14 18:06:01 Error: Fatal Error (1): Maximum execution time of 30 seconds exceeded in [C:\xampp\htdocs\cakephp\lib\Cake\Error\ErrorHandler.php, line 196]
2013-12-14 18:06:01 Error: [FatalErrorException] Maximum execution time of 30 seconds exceeded
Request URL: /cakephp/
Stack Trace:
#0 C:\xampp\htdocs\cakephp\lib\Cake\Error\ErrorHandler.php(203): ErrorHandler::handleFatalError(1, 'Maximum executi...', 'C:\xampp\htdocs...', 196)
#1 [internal function]: ErrorHandler::handleError(1, 'Maximum executi...', 'C:\xampp\htdocs...', 196, Array)
#2 C:\xampp\htdocs\cakephp\lib\Cake\Core\App.php(929): call_user_func('ErrorHandler::h...', 1, 'Maximum executi...', 'C:\xampp\htdocs...', 196, Array)
#3 C:\xampp\htdocs\cakephp\lib\Cake\Core\App.php(902): App::_checkFatalError()
#4 [internal function]: App::shutdown()
#5 {main}
2013-12-14 18:06:43 Error: Fatal Error (1): Maximum execution time of 30 seconds exceeded in [C:\xampp\htdocs\cakephp\lib\Cake\Error\ErrorHandler.php, line 196]
2013-12-14 18:06:43 Error: [FatalErrorException] Maximum execution time of 30 seconds exceeded
Request URL: /cakephp/
Stack Trace:
#0 C:\xampp\htdocs\cakephp\lib\Cake\Error\ErrorHandler.php(203): ErrorHandler::handleFatalError(1, 'Maximum executi...', 'C:\xampp\htdocs...', 196)
#1 [internal function]: ErrorHandler::handleError(1, 'Maximum executi...', 'C:\xampp\htdocs...', 196, Array)
#2 C:\xampp\htdocs\cakephp\lib\Cake\Core\App.php(929): call_user_func('ErrorHandler::h...', 1, 'Maximum executi...', 'C:\xampp\htdocs...', 196, Array)
#3 C:\xampp\htdocs\cakephp\lib\Cake\Core\App.php(902): App::_checkFatalError()
#4 [internal function]: App::shutdown()
#5 {main}
2013-12-14 18:08:55 Error: Fatal Error (1): Maximum execution time of 30 seconds exceeded in [C:\xampp\htdocs\cakephp\lib\Cake\Error\ErrorHandler.php, line 196]
2013-12-14 18:08:55 Error: [FatalErrorException] Maximum execution time of 30 seconds exceeded
Request URL: /cakephp/
Stack Trace:
#0 C:\xampp\htdocs\cakephp\lib\Cake\Error\ErrorHandler.php(203): ErrorHandler::handleFatalError(1, 'Maximum executi...', 'C:\xampp\htdocs...', 196)
#1 [internal function]: ErrorHandler::handleError(1, 'Maximum executi...', 'C:\xampp\htdocs...', 196, Array)
#2 C:\xampp\htdocs\cakephp\lib\Cake\Core\App.php(929): call_user_func('ErrorHandler::h...', 1, 'Maximum executi...', 'C:\xampp\htdocs...', 196, Array)
#3 C:\xampp\htdocs\cakephp\lib\Cake\Core\App.php(902): App::_checkFatalError()
#4 [internal function]: App::shutdown()
#5 {main}
2013-12-14 18:10:30 Error: Fatal Error (1): Maximum execution time of 30 seconds exceeded in [C:\xampp\htdocs\cakephp\lib\Cake\Error\ErrorHandler.php, line 196]
2013-12-14 18:10:30 Error: [FatalErrorException] Maximum execution time of 30 seconds exceeded
Request URL: /cakephp/
Stack Trace:
#0 C:\xampp\htdocs\cakephp\lib\Cake\Error\ErrorHandler.php(203): ErrorHandler::handleFatalError(1, 'Maximum executi...', 'C:\xampp\htdocs...', 196)
#1 [internal function]: ErrorHandler::handleError(1, 'Maximum executi...', 'C:\xampp\htdocs...', 196, Array)
#2 C:\xampp\htdocs\cakephp\lib\Cake\Core\App.php(929): call_user_func('ErrorHandler::h...', 1, 'Maximum executi...', 'C:\xampp\htdocs...', 196, Array)
#3 C:\xampp\htdocs\cakephp\lib\Cake\Core\App.php(902): App::_checkFatalError()
#4 [internal function]: App::shutdown()
#5 {main}
2013-12-14 18:18:32 Error: Fatal Error (1): Maximum execution time of 30 seconds exceeded in [C:\xampp\htdocs\cakephp\lib\Cake\Error\ErrorHandler.php, line 196]
2013-12-14 18:18:32 Error: [FatalErrorException] Maximum execution time of 30 seconds exceeded
Request URL: /cakephp/
Stack Trace:
#0 C:\xampp\htdocs\cakephp\lib\Cake\Error\ErrorHandler.php(203): ErrorHandler::handleFatalError(1, 'Maximum executi...', 'C:\xampp\htdocs...', 196)
#1 [internal function]: ErrorHandler::handleError(1, 'Maximum executi...', 'C:\xampp\htdocs...', 196, Array)
#2 C:\xampp\htdocs\cakephp\lib\Cake\Core\App.php(929): call_user_func('ErrorHandler::h...', 1, 'Maximum executi...', 'C:\xampp\htdocs...', 196, Array)
#3 C:\xampp\htdocs\cakephp\lib\Cake\Core\App.php(902): App::_checkFatalError()
#4 [internal function]: App::shutdown()
#5 {main}
2013-12-14 18:38:09 Error: [MissingActionException] Action PostsController::view() could not be found.
Exception Attributes: array (
  'controller' => 'PostsController',
  'action' => 'view',
)
Request URL: /cakephp/posts/view/1
Stack Trace:
#0 C:\xampp\htdocs\cakephp\lib\Cake\Routing\Dispatcher.php(185): Controller->invokeAction(Object(CakeRequest))
#1 C:\xampp\htdocs\cakephp\lib\Cake\Routing\Dispatcher.php(160): Dispatcher->_invoke(Object(PostsController), Object(CakeRequest), Object(CakeResponse))
#2 C:\xampp\htdocs\cakephp\app\webroot\index.php(108): Dispatcher->dispatch(Object(CakeRequest), Object(CakeResponse))
#3 {main}
2013-12-15 03:53:02 Error: [MissingControllerException] Controller class CakephpController could not be found.
Exception Attributes: array (
  'class' => 'CakephpController',
  'plugin' => NULL,
)
Request URL: /cakephp/Cakephp/
Stack Trace:
#0 C:\xampp\htdocs\cakephp\app\webroot\index.php(108): Dispatcher->dispatch(Object(CakeRequest), Object(CakeResponse))
#1 {main}
2013-12-15 04:43:57 Error: [MissingActionException] Action PostsController::view() could not be found.
Exception Attributes: array (
  'controller' => 'PostsController',
  'action' => 'view',
)
Request URL: /studentcake/posts/view/1
Stack Trace:
#0 C:\xampp\htdocs\cakephp\lib\Cake\Routing\Dispatcher.php(185): Controller->invokeAction(Object(CakeRequest))
#1 C:\xampp\htdocs\cakephp\lib\Cake\Routing\Dispatcher.php(160): Dispatcher->_invoke(Object(PostsController), Object(CakeRequest), Object(CakeResponse))
#2 C:\xampp\htdocs\studentcake\webroot\index.php(112): Dispatcher->dispatch(Object(CakeRequest), Object(CakeResponse))
#3 {main}
2013-12-15 05:04:06 Error: [MissingControllerException] Controller class PhpStorm-e4d52f59-c7ad-48e0-84cd-eba7d2f917bf.phpController could not be found.
Exception Attributes: array (
  'class' => 'PhpStorm-e4d52f59-c7ad-48e0-84cd-eba7d2f917bf.phpController',
  'plugin' => NULL,
)
Request URL: /blogtestcake/PhpStorm-e4d52f59-c7ad-48e0-84cd-eba7d2f917bf.php
Stack Trace:
#0 C:\xampp\htdocs\blogtestcake\webroot\index.php(112): Dispatcher->dispatch(Object(CakeRequest), Object(CakeResponse))
#1 {main}
2013-12-15 14:29:15 Error: [NotFoundException] Invalid post
Request URL: /blogtestcake/posts/view/
Stack Trace:
#0 [internal function]: PostsController->view()
#1 C:\xampp\htdocs\cakephp\lib\Cake\Controller\Controller.php(490): ReflectionMethod->invokeArgs(Object(PostsController), Array)
#2 C:\xampp\htdocs\cakephp\lib\Cake\Routing\Dispatcher.php(185): Controller->invokeAction(Object(CakeRequest))
#3 C:\xampp\htdocs\cakephp\lib\Cake\Routing\Dispatcher.php(160): Dispatcher->_invoke(Object(PostsController), Object(CakeRequest), Object(CakeResponse))
#4 C:\xampp\htdocs\blogtestcake\webroot\index.php(112): Dispatcher->dispatch(Object(CakeRequest), Object(CakeResponse))
#5 {main}
2013-12-15 19:21:34 Error: Fatal Error (1): Call to a member function allow() on a non-object in [C:\xampp\htdocs\blogtestcake\Controller\UsersController.php, line 16]
2013-12-15 19:21:34 Error: [FatalErrorException] Call to a member function allow() on a non-object
Request URL: /blogtestcake/Users
Stack Trace:
#0 C:\xampp\htdocs\cakephp\lib\Cake\Error\ErrorHandler.php(203): ErrorHandler::handleFatalError(1, 'Call to a membe...', 'C:\xampp\htdocs...', 16)
#1 [internal function]: ErrorHandler::handleError(1, 'Call to a membe...', 'C:\xampp\htdocs...', 16, Array)
#2 C:\xampp\htdocs\cakephp\lib\Cake\Core\App.php(929): call_user_func('ErrorHandler::h...', 1, 'Call to a membe...', 'C:\xampp\htdocs...', 16, Array)
#3 C:\xampp\htdocs\cakephp\lib\Cake\Core\App.php(902): App::_checkFatalError()
#4 [internal function]: App::shutdown()
#5 {main}
2013-12-15 19:21:58 Error: Fatal Error (1): Call to a member function allow() on a non-object in [C:\xampp\htdocs\blogtestcake\Controller\UsersController.php, line 16]
2013-12-15 19:21:58 Error: [FatalErrorException] Call to a member function allow() on a non-object
Request URL: /blogtestcake/Users/Add
Stack Trace:
#0 C:\xampp\htdocs\cakephp\lib\Cake\Error\ErrorHandler.php(203): ErrorHandler::handleFatalError(1, 'Call to a membe...', 'C:\xampp\htdocs...', 16)
#1 [internal function]: ErrorHandler::handleError(1, 'Call to a membe...', 'C:\xampp\htdocs...', 16, Array)
#2 C:\xampp\htdocs\cakephp\lib\Cake\Core\App.php(929): call_user_func('ErrorHandler::h...', 1, 'Call to a membe...', 'C:\xampp\htdocs...', 16, Array)
#3 C:\xampp\htdocs\cakephp\lib\Cake\Core\App.php(902): App::_checkFatalError()
#4 [internal function]: App::shutdown()
#5 {main}
2013-12-15 19:22:07 Error: Fatal Error (1): Call to a member function allow() on a non-object in [C:\xampp\htdocs\blogtestcake\Controller\UsersController.php, line 16]
2013-12-15 19:22:07 Error: [FatalErrorException] Call to a member function allow() on a non-object
Request URL: /blogtestcake/Users/add
Stack Trace:
#0 C:\xampp\htdocs\cakephp\lib\Cake\Error\ErrorHandler.php(203): ErrorHandler::handleFatalError(1, 'Call to a membe...', 'C:\xampp\htdocs...', 16)
#1 [internal function]: ErrorHandler::handleError(1, 'Call to a membe...', 'C:\xampp\htdocs...', 16, Array)
#2 C:\xampp\htdocs\cakephp\lib\Cake\Core\App.php(929): call_user_func('ErrorHandler::h...', 1, 'Call to a membe...', 'C:\xampp\htdocs...', 16, Array)
#3 C:\xampp\htdocs\cakephp\lib\Cake\Core\App.php(902): App::_checkFatalError()
#4 [internal function]: App::shutdown()
#5 {main}
2013-12-15 19:40:27 Error: [MissingViewException] View file "C:\xampp\htdocs\blogtestcake\\View\Users\index.ctp" is missing.
Exception Attributes: array (
  'file' => 'C:\\xampp\\htdocs\\blogtestcake\\\\View\\Users\\index.ctp',
)
Request URL: /blogtestcake/users
Stack Trace:
#0 C:\xampp\htdocs\cakephp\lib\Cake\View\View.php(457): View->_getViewFileName(NULL)
#1 C:\xampp\htdocs\cakephp\lib\Cake\Controller\Controller.php(952): View->render(NULL, NULL)
#2 C:\xampp\htdocs\cakephp\lib\Cake\Routing\Dispatcher.php(192): Controller->render()
#3 C:\xampp\htdocs\cakephp\lib\Cake\Routing\Dispatcher.php(160): Dispatcher->_invoke(Object(UsersController), Object(CakeRequest), Object(CakeResponse))
#4 C:\xampp\htdocs\blogtestcake\webroot\index.php(112): Dispatcher->dispatch(Object(CakeRequest), Object(CakeResponse))
#5 {main}
2013-12-15 20:11:38 Error: [MissingViewException] View file "C:\xampp\htdocs\blogtestcake\\View\Users\index.ctp" is missing.
Exception Attributes: array (
  'file' => 'C:\\xampp\\htdocs\\blogtestcake\\\\View\\Users\\index.ctp',
)
Request URL: /blogtestcake/users
Stack Trace:
#0 C:\xampp\htdocs\cakephp\lib\Cake\View\View.php(457): View->_getViewFileName(NULL)
#1 C:\xampp\htdocs\cakephp\lib\Cake\Controller\Controller.php(952): View->render(NULL, NULL)
#2 C:\xampp\htdocs\cakephp\lib\Cake\Routing\Dispatcher.php(192): Controller->render()
#3 C:\xampp\htdocs\cakephp\lib\Cake\Routing\Dispatcher.php(160): Dispatcher->_invoke(Object(UsersController), Object(CakeRequest), Object(CakeResponse))
#4 C:\xampp\htdocs\blogtestcake\webroot\index.php(112): Dispatcher->dispatch(Object(CakeRequest), Object(CakeResponse))
#5 {main}
2013-12-15 20:22:28 Error: [MissingControllerException] Controller class LogoutController could not be found.
Exception Attributes: array (
  'class' => 'LogoutController',
  'plugin' => NULL,
)
Request URL: /blogtestcake/logout
Stack Trace:
#0 C:\xampp\htdocs\blogtestcake\webroot\index.php(112): Dispatcher->dispatch(Object(CakeRequest), Object(CakeResponse))
#1 {main}
2013-12-15 20:29:41 Error: [MissingActionException] Action UsersController::lougout() could not be found.
Exception Attributes: array (
  'controller' => 'UsersController',
  'action' => 'lougout',
)
Request URL: /blogtestcake/users/lougout
Stack Trace:
#0 C:\xampp\htdocs\cakephp\lib\Cake\Routing\Dispatcher.php(185): Controller->invokeAction(Object(CakeRequest))
#1 C:\xampp\htdocs\cakephp\lib\Cake\Routing\Dispatcher.php(160): Dispatcher->_invoke(Object(UsersController), Object(CakeRequest), Object(CakeResponse))
#2 C:\xampp\htdocs\blogtestcake\webroot\index.php(112): Dispatcher->dispatch(Object(CakeRequest), Object(CakeResponse))
#3 {main}
2013-12-22 00:04:51 Error: [MissingControllerException] Controller class RulerController could not be found.
Exception Attributes: array (
  'class' => 'RulerController',
  'plugin' => NULL,
)
Request URL: /Ruler/ruler/
Stack Trace:
#0 C:\xampp\htdocs\Ruler\webroot\index.php(112): Dispatcher->dispatch(Object(CakeRequest), Object(CakeResponse))
#1 {main}
2013-12-22 00:10:18 Error: [MissingControllerException] Controller class PhpStorm-75604e9e-0675-4cd9-a9fb-58d6c87845dc.phpController could not be found.
Exception Attributes: array (
  'class' => 'PhpStorm-75604e9e-0675-4cd9-a9fb-58d6c87845dc.phpController',
  'plugin' => NULL,
)
Request URL: /Ruler/PhpStorm-75604e9e-0675-4cd9-a9fb-58d6c87845dc.php
Stack Trace:
#0 C:\xampp\htdocs\Ruler\webroot\index.php(112): Dispatcher->dispatch(Object(CakeRequest), Object(CakeResponse))
#1 {main}
2013-12-22 00:41:36 Error: [MissingControllerException] Controller class BlogController could not be found.
Exception Attributes: array (
  'class' => 'BlogController',
  'plugin' => NULL,
)
Request URL: /Ruler/blog
Stack Trace:
#0 C:\xampp\htdocs\Ruler\webroot\index.php(112): Dispatcher->dispatch(Object(CakeRequest), Object(CakeResponse))
#1 {main}
2013-12-22 00:41:50 Error: [MissingControllerException] Controller class PostController could not be found.
Exception Attributes: array (
  'class' => 'PostController',
  'plugin' => NULL,
)
Request URL: /Ruler/Post
Stack Trace:
#0 C:\xampp\htdocs\Ruler\webroot\index.php(112): Dispatcher->dispatch(Object(CakeRequest), Object(CakeResponse))
#1 {main}
